Repository adc-connect/adcc, pull requests merged in 2019-10, with the labels that each got.

#1 Bugfix for MacOS installs from pip
  docs/installation.rst
  extension/AdcCore.py
  scripts/upload_core.py
  setup.py
Labels: bug

#7 Unify strings in setup.py
  README.md
  setup.py
Labels: documentation

#8 Add rudimentary Travis CI file
  .travis.yml
  adcc/AdcMethod.py
  adcc/backends/available_backends.py
  adcc/caching_policy.py
  adcc/conftest.py
  adcc/lib
  adcc/lib/.gitignore
  adcc/lib/libadccore_LICENSE
  adcc/test_contract.py
  examples/water/pyscf_ccpvdz_adc3_comparison.py
  extension/adccore/.gitignore
  extension/adccore/lib
  setup.cfg
Labels: enhancement

#10 Autocheckout of adccore
  .travis.yml
  docs/developers.rst
  docs/installation.rst
  extension/AdcCore.py
Labels: documentation, enhancement

#15 [WIP] Clang support
  .travis.yml
  adcc/backends/available_backends.py
  docs/installation.rst
  extension/convert_timer.cc
  extension/export_CachingPolicy.cc
  extension/export_HartreeFockProvider.cc
  extension/export_MoSpaces.cc
  extension/export_OneParticleOperator.cc
  extension/export_ReferenceState.cc
  extension/export_Symmetry.cc
  extension/export_Tensor.cc
  setup.py
Labels: adccore, feature
