Repository adc-connect/adcc, pull requests merged in 2020-06, with the labels that each got.

#74 Amend modified transition moments
  adcc/modified_transition_moments.py
  adcc/test_modified_transition_moments.py
Labels: feature, properties

#77 Move MTMs, diffdms and transition dms to python
  .travis.yml
  adcc/ExcitedStates.py
  adcc/OneParticleOperator.py
  adcc/ReferenceState.py
  adcc/adc_pp/__init__.py
  adcc/adc_pp/modified_transition_moments.py
  adcc/adc_pp/state2state_transition_dm.py
  adcc/adc_pp/state_diffdm.py
  adcc/adc_pp/test_modified_transition_moments.py
  adcc/adc_pp/transition_dm.py
  adcc/block.py
  adcc/functions.py
  adcc/modified_transition_moments.py
  adcc/opt_einsum_integration.py
  adcc/state_densities.py
  adcc/test_Tensor.py
  adcc/test_einsum.py
  adcc/workflow.py
  extension/export_AdcMatrix.cc
  extension/export_OneParticleOperator.cc
  extension/export_Tensor.cc
  setup.py
Labels: adccore, properties, question

#79 AdcMatrix block-wise tests
  adcc/AmplitudeVector.py
  adcc/test_AdcMatrix.py
  adcc/test_dense_export.py
  adcc/testdata/SHA256SUMS
  adcc/testdata/dump_reference_adcc.py
Labels: testing

#78 Pandas DataFrame export
  adcc/Excitation.py
  adcc/ExcitedStates.py
  adcc/test_ExcitedStates.py
  conda/meta.yaml.in
  setup.py
Labels: feature

#62 More documentation
  docs/about.rst
  docs/zpublications.rst
  examples/0_basics/00_Overview.ipynb
  examples/0_basics/01_Backends.ipynb
  examples/0_basics/03_Tweaks.ipynb
  examples/0_basics/h2o_sto3g_hfdata.hdf5
Labels: documentation
